### ISSUE TITLE
auto complete hex too fast

### ISSUE THREAD

**Issue by Helloooooooooo** [xiaokaike/vue-color#66] opened 2017-05-26 08:38 UTC
I want to input #B2B2B2, it will auto complete to BB22BB

**Comment by mirshko** [comment] 2017-05-26 13:04
Dupe of #65

**Comment by xiaokaike** [comment] 2017-06-03 03:34
fix 
https://github.com/xiaokaike/vue-color/pull/70

**Closed by xiaokaike** 2017-06-03 03:34 UTC
